staging-settings:
  user-workflow:
    workflow-name: "hop-query-staging"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.runtime.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "hop-query-production"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
