/** Short UI hints. Labels and steps only. */
export const FLOW = [
  "choose a question",
  "pay once",
  "get a clear answer",
] as const;

export const HELP = {
  ask: "Choose a business question. Hop compares live data with your private limit.",
  mic: "Speak your question.",
  risk: "Check two lending books against your private limit.",
  insurance: "Check this period's incidents against your private limit.",
  trade: "Check a live reading against your private cutoff.",
  tvl: "Check the combined market size against your private floor.",
  wall: "See whether cash is below the operating buffer.",
  check: "Run the check. A small Hedera payment may be requested.",
  confirm: "Approve this payment to continue.",
  stamp: "Your clear result appears here.",
  observed: "The public number used for this result.",
  hashscan: "Open the public payment record.",
  agent: "Optional settings for an agent. Most people can leave this closed.",
  query: "The kind of check sent to Hop.",
  protocols: "The public data sources used for the check.",
  lag: "How fresh the market data must be.",
  xpay: "Advanced: paste a signed payment from an agent.",
  world: "Optional human verification.",
  mute: "Turn off the spoken result.",
  trace: "See each step as the request runs.",
  evidence: "Your receipt: result, payment, data source, and proof.",
  export: "Download your receipt.",
  peac: "Download a receipt made for agents.",
  verify: "Check that the receipt proof is still valid.",
  graph: "Public market data used by the check.",
  hedera: "Network that handles the payment.",
  cre: "Private check that keeps your limit hidden.",
  worldRail: "Shows when human verification was used.",
  mandate: "Spending limit for the agent.",
  hcs: "A receipt fingerprint saved on Hedera.",
  amount: "Price of one check.",
  liveData: "Live Graph lending data is ready.",
  payment: "One small payment settles on Hedera.",
  privateCheck: "Your limit stays private during the check.",
} as const;

export const STATUS_LABEL: Record<string, string> = {
  unpaid: "Payment needed",
  pending: "Checking…",
  policy_unavailable: "Private limit unavailable",
  graph_unconfigured: "Live data unavailable",
  cre_unavailable: "CRE runner unavailable",
  facilitator_unavailable: "Payment service unavailable",
  merchant_unconfigured: "Payment account unavailable",
  mandate_review: "Approval needed",
  mandate_denied: "Agent spending limit reached",
  rate_limited: "Please wait a moment",
  payer_denied: "Payment not approved",
  world_required: "Human verification needed",
  passport_required: "Agent passport required",
  passport_denied: "Agent passport denied",
  did_invalid: "DID invalid",
  erc8004_invalid: "ERC-8004 invalid",
  did_mismatch: "DID mismatch",
  erc8004_mismatch: "ERC-8004 mismatch",
  stale: "Data is too old",
  k_anon_denied: "Not enough data to show",
};

export const STATUS_HELP: Record<string, string> = {
  unpaid: "Approve the small payment to continue.",
  pending: "Hop is checking the live data now.",
  policy_unavailable: "The private limit is not ready, so no check can run.",
  graph_unconfigured: "The live market data source is not connected.",
  cre_unavailable: "The CRE CLI is not available to the API. No payment was taken.",
  facilitator_unavailable: "The payment service is temporarily unavailable.",
  merchant_unconfigured: "The payment account is not configured.",
  mandate_review: "The agent needs approval before spending more.",
  mandate_denied: "The agent reached its allowed spending limit.",
  rate_limited: "Too many checks came in at once.",
  payer_denied: "This payment account is not approved.",
  world_required: "Complete human verification to continue.",
  passport_required: "Issue a Hop passport and send X-Hop-Passport.",
  passport_denied: "The passport is invalid, expired, or revoked.",
  did_invalid: "DID syntax is invalid.",
  erc8004_invalid: "ERC-8004 agent id or registry is invalid.",
  did_mismatch: "X-Hop-Did does not match the passport DID.",
  erc8004_mismatch: "X-Hop-Erc8004 does not match the passport ERC-8004.",
  stale: "The data was too old. The check still completed as paid.",
  k_anon_denied: "There were not enough accounts to safely show this result.",
};
