/** Short UI hints. Labels and steps only. */
export const FLOW = [
  "query dataset privately",
  "pay a tiny fee",
  "stamp over / not over",
] as const;

export const HELP = {
  ask: "Type or speak a yes/no. We check live numbers against your hidden limit.",
  mic: "Speak the question instead of typing.",
  risk: "Are both lending books over your hidden limit?",
  insurance: "Did incidents this window go past your hidden limit?",
  trade: "Does the live reading pass your hidden cutoff?",
  tvl: "Is combined size under your hidden floor?",
  wall: "After a paid check: is cash below your buffer?",
  check: "Pay a few cents on Hedera. You get over or not over. Your limit stays hidden.",
  confirm: "This check is over the auto-pay cap. Tap to allow it.",
  stamp: "The yes/no. You see public totals only — never your limit.",
  observed: "The public number we compared. Not your limit.",
  hashscan: "Proof the tiny payment landed on Hedera.",
  agent: "Knobs for bots: which check, which books, how old data can be, payment.",
  query: "Kind of check. Desks use policy_check.",
  protocols: "Which lending books to look at.",
  lag: "How old the numbers can be. Bigger = older is ok.",
  xpay: "Paste a signed Hedera payment. Blank is ok if demo sign is on.",
  world: "Optional. Prove you are a unique human.",
  mute: "Stop the voice reading the stamp.",
  trace: "Live log of the market pull, the payment, and the locked check.",
  evidence: "Receipt you keep: paid, which market, which block. No wallets. No limit.",
  export: "Download the receipt.",
  peac: "Same receipt in a standard shape agents can file.",
  verify: "Check the receipt hashes still match.",
  graph: "Public lending numbers anyone can look up.",
  hedera: "Where the tiny payment settles.",
  cre: "Locked drawer that holds your limit. The limit never leaves.",
  worldRail: "Lights up if a unique-human proof was used.",
  mandate: "Spending cap for the agent. The AI cannot pay past this.",
  hcs: "A hash of the receipt posted on Hedera.",
  amount: "Price of one check, in tinybars.",
} as const;

export const STATUS_HELP: Record<string, string> = {
  unpaid: "Needs a tiny payment first.",
  pending: "Checking now.",
  policy_unavailable: "No house limit loaded. Cannot check.",
  graph_unconfigured: "Live market numbers are not hooked up.",
  facilitator_unavailable: "Payment desk is down.",
  merchant_unconfigured: "No pay-to account set.",
  mandate_review: "Over the auto-pay cap. Confirm to pay.",
  mandate_denied: "This check is not allowed by the spending cap.",
  rate_limited: "Too many checks. Wait a moment.",
  payer_denied: "This payer is not on the list.",
  world_required: "Need a unique-human proof first.",
  stale: "Numbers were too old. You still paid.",
  k_anon_denied: "Too few accounts in that bucket to show.",
};
